<div class="page-root"><div class="page-section">
<div class="thank-you thank-you-payment-type-offline">
<div class="thank-you-heading" data-spm-anchor-id="a2o4j.transaction_result.0.i7.77696664Nc9Lyd">
<div class="thank-you-icon">
<svg class="svgfont " aria-hidden="true" data-spm-anchor-id="a2o4j.transaction_result.0.i8.77696664Nc9Lyd">
<use xlink:href="#lazada-ic-time"></use></svg>
</div>Terima kasih untuk pembelian anda!</div>
<div class="thank-you-secondary-container">
<div class="thank-you-secondary-heading" data-spm="order_detail">
<div class="thank-you-order-number-container"><span>Nomor pesanan anda </span><span class="thank-you-order-number">207037278184051</span></div><a id="automation-link-track-order" class="automation-link thank-you-track-order-link" href="https://my.lazada.co.id/customer/order/view/?tradeOrderId=207037278184051&amp;buyerEmail=rizkiamallia25%40gmail.com">CEK STATUS PESANAN</a></div><div class="thank-you-instruction">Anda dapat melacak dan mengatur pesanan Anda di
<a id="automation-link-management-order" class="automation-link thank-you-instruction-link" href="https://my.lazada.co.id/customer/order/index/">Akun Saya &gt; Pesanan Saya
</a></div></div></div></div><div class="page-section"><div class="payment-amount wrapper"><div class="payment-amount container"><div class="payment-amount title">Mohon untuk menyiapkan uang sejumlah informasi dibawah ini pada saat pengiriman</div><div class="payment-amount amount">Rp62.000</div></div></div><div class="payment-information wrapper"><div class="payment-information container"><div class="payment-information item"><span class="lazada lazada-Email lazada-icon payment-information icon"></span><div class="payment-information content"><div class="payment-information text-content"><div class="payment-information text-line"><span>Kami telah mengirimkan email konfirmasi ke </span><span class="payment-information strong-text">rizkiamallia25@gmail.com</span><span> dengan detail pesanan</span></div></div></div></div><div class="payment-information item"><span class="lazada lazada-ic-Express lazada-icon payment-information icon"></span><div class="payment-information content"><div class="payment-information text-content"><div class="payment-information text-line"><span>Pesanan anda akan dikirimkan pada </span><span class="payment-information strong-text">Rab 04 Jul-Sen 09 Jul</span></div></div></div></div></div></div><div class="order-summary"><div class="checkout-summary"><div id="automation-checkout-summary-heading-button" class="checkout-summary-heading collapsed"><div class="checkout-summary-row"><div class="checkout-summary-label-collapse">Ringkasan pesanan</div><div class="checkout-summary-value-collapse">Rp62.000</div></div><span class="lazada lazada-ic-Arrow-Down lazada-icon checkout-summary-icon"></span></div></div></div><div class="button-container" data-spm="continue_shopping"><a id="automation-link-button_1" href="https://www.lazada.co.id" class="next-btn next-btn-primary next-btn-large automation-link automation-btn-continue-shopping">LANJUTKAN BELANJA
</a></div></div></div>